// Auto-generated 2026-08-10 from a full manual/LLM audit of all product-sourcing
// recommendation candidates (3,784 items across 83 product types). Each entry below
// is a (product_type, product_group_key) pair confirmed to be a category mismatch
// caused by upstream crawling/matching errors (e.g. a canned-tuna product tagged
// under the "extra virgin olive oil" product_type because its packaging text
// mentions "extra virgin oil"). These do NOT belong in the 추천 요약 cards, but are
// left untouched in the main table. Do not hand-edit this file piecemeal; regenerate
// it by re-running the same full-scan audit if the underlying data changes materially.
export const RECOMMENDATION_EXCLUDED_PAIRS = new Set([
  "A1스테이크소스||kanetsu_bussan_konjac_steak",
  "AGROMONTE 토마토 파스타 소스||benissimo_basil_sun_dried_tomato_oil",
  "CAVENDISH 크리스피 스파이시||agape_organic_french_bean",
  "CAVENDISH 크리스피 스파이시||ava_pewangi_softener_french_peony",
  "CAVENDISH 크리스피 스파이시||baba_red_flower_french_bean",
  "CAVENDISH 크리스피 스파이시||bestari_fried_chicken_coating_hot_spicy",
  "CAVENDISH 크리스피 스파이시||bibigo_bundle_stir_fried_ramyun_spicy_tteokbokki_4x122g",
  "CAVENDISH 크리스피 스파이시||chitose_sanchoku_french_bean",
  "CAVENDISH 크리스피 스파이시||cp_crispy_fried_chicken_hot_spicy",
  "CAVENDISH 크리스피 스파이시||daiso_french_embroidery_needle",
  "CAVENDISH 크리스피 스파이시||daiso_french_twist_comb",
  "CAVENDISH 크리스피 스파이시||daiso_french_watering_pot",
  "CAVENDISH 크리스피 스파이시||delica_spicy_fried_chicken",
  "CAVENDISH 크리스피 스파이시||downy_french_lavender",
  "CAVENDISH 크리스피 스파이시||eb_kranch_hot_spicy_fried_chicken",
  "CAVENDISH 크리스피 스파이시||edsam_french_bean",
  "CAVENDISH 크리스피 스파이시||farcent_bundle_scented_spray_french_romance_2x250ml",
  "CAVENDISH 크리스피 스파이시||farms_essence_spicy_roasted_chicken_drumstick_rice",
  "CAVENDISH 크리스피 스파이시||farms_essence_spicy_roasted_chicken_rices",
  "CAVENDISH 크리스피 스파이시||febreze_purple_french_violet_grapefruit",
  "CAVENDISH 크리스피 스파이시||first_pride_crispy_golden_fried_chicken_hot_spicy",
  "CAVENDISH 크리스피 스파이시||french_beans_250",
  "CAVENDISH 크리스피 스파이시||haidilao_spicy_stir_fry_sauce",
  "CAVENDISH 크리스피 스파이시||loreal_excellence_fashion_p66_intense_spicy_red",
  "CAVENDISH 크리스피 스파이시||mi_sedaap_bundle_goreng_korean_spicy_chicken_fried_ramen_5x87g",
  "CAVENDISH 크리스피 스파이시||old_bay_bundle_hot_sauce_5oz_12pack",
  "CAVENDISH 크리스피 스파이시||otafuku_sweet_spicy_okonomi_sauce",
  "CAVENDISH 크리스피 스파이시||signature_fried_chicken_whole_leg_spicy",
  "CAVENDISH 크리스피 스파이시||spicy_noodle_web_latiao_snacks",
  "CAVENDISH 크리스피 스파이시||st_dalfour_fruit_spread_french_grape",
  "CAVENDISH 크리스피 스파이시||sushi_onigiri_hot_spicy_chicken_floss",
  "CAVENDISH 크리스피 스파이시||tao_kae_noi_crispy_fried_seaweed_hot_spicy",
  "CAVENDISH 크리스피 스파이시||winners_hot_spicy_fried_chicken_flour",
  "CP 통새우완탕||caribbean_food_jamaican_beef_turnovers",
  "CP 통새우완탕||delizios_bonito_snapper",
  "CP 통새우완탕||mccrum_straight_cut_fries",
  "CP 통새우완탕||pantai_cantonese_suki_sauce",
  "CP 통새우완탕||smart_heart_cat_tuna_shrimp",
  "CP 통새우완탕||temptations_cat_treats",
  "CP 통새우완탕||ty_ling_hot_mustard_sauce",
  "CP 플레이밍 치킨 텐더||fancy_feast_pate_kitten_tender_chicken",
  "CP 플레이밍 치킨 텐더||hatakenomikata_manma_nikujaga",
  "CP 플레이밍 치킨 텐더||kewpie_happy_recipe_hokkaido_corn_chicken_stew",
  "CP 플레이밍 치킨 텐더||kewpie_konsai_sasami",
  "CP 플레이밍 치킨 텐더||kewpie_nikoniko_chikuzenni_bento",
  "CP 플레이밍 치킨 텐더||kewpie_nikoniko_liver_tomato_bento",
  "CP 플레이밍 치킨 텐더||kewpie_nikoniko_nikujaga_bento",
  "CP 플레이밍 치킨 텐더||kewpie_nikoniko_osakana_sasami",
  "CP 플레이밍 치킨 텐더||kewpie_nikoniko_pakupaku_yofu_bento",
  "CP 플레이밍 치킨 텐더||kewpie_nikoniko_torigayu_osakana",
  "CP 플레이밍 치킨 텐더||kewpie_sasami_ryokuoshoku_yasai",
  "CP 플레이밍 치킨 텐더||libbys_chicken_vienna_sausage",
  "CP 플레이밍 치킨 텐더||military_surplus_freeze_dried_biscuits",
  "CP 플레이밍 치킨 텐더||old_bay_seasoning",
  "CP 플레이밍 치킨 텐더||sheba_tender_chicken_fine_flakes",
  "CP 플레이밍 치킨 텐더||spot_farms_basic_chicken_tenders",
  "CP 플레이밍 치킨 텐더||valley_fresh_chicken_breast_in_water",
  "CP 플레이밍 치킨 텐더||waggin_train_chicken_jerky_tenders",
  "CP 플레이밍 치킨 텐더||wakodo_global_kenchin_udon",
  "CP 플레이밍 치킨 텐더||wakodo_sonomama_sauce_kabocha",
  "CP 플레이밍 치킨 텐더||wakodo_sonomama_sozai_sasami",
  "GENERAL MILLS 골든그레이엄||general_mills_bisquick_original",
  "GENERAL MILLS 골든그레이엄||nutella_hazelnutspread",
  "GENERAL MILLS 골든그레이엄||pbfit_classicpowder_1_87lb",
  "GENERAL MILLS 골든그레이엄||skippy_creamy_48oz2pk",
  "GENERAL MILLS 골든그레이엄||welchs_concordgrapejelly",
  "GENERAL MILLS 후르츠 롤업 젤리||cutie_compacttoiletroll_2x10",
  "GENERAL MILLS 후르츠 롤업 젤리||cutie_softtoiletroll_30",
  "GENERAL MILLS 후르츠 롤업 젤리||daiso_carpetcleaningtape_spiral_90",
  "GENERAL MILLS 후르츠 롤업 젤리||daiso_refillroll_lintroller_90",
  "GENERAL MILLS 후르츠 롤업 젤리||daiso_refillroll_lintroller_floor_50",
  "GENERAL MILLS 후르츠 롤업 젤리||daiso_refillroll_lintroller_pethair_50",
  "GENERAL MILLS 후르츠 롤업 젤리||frollies_watermelonpineappleicepops",
  "GENERAL MILLS 후르츠 롤업 젤리||kleenex_bathtissue_regular_3ply_30",
  "GENERAL MILLS 후르츠 롤업 젤리||kleenex_bathtissue_ultrasoftaloevera_20",
  "GENERAL MILLS 후르츠 롤업 젤리||kleenex_bathtissue_ultrasoftfresh_20",
  "GENERAL MILLS 후르츠 롤업 젤리||kleenex_bathtissue_ultrasoftregular_10",
  "GENERAL MILLS 후르츠 롤업 젤리||kleenex_bathtissue_ultrasoftregular_20",
  "GENERAL MILLS 후르츠 롤업 젤리||kleenex_bathtissue_ultrasoftthick_4ply_20",
  "GENERAL MILLS 후르츠 롤업 젤리||lays_stax_original",
  "GENERAL MILLS 후르츠 롤업 젤리||lays_stax_smokinbbq",
  "GENERAL MILLS 후르츠 롤업 젤리||premier_floraltoiletroll_300s_10",
  "GENERAL MILLS 후르츠 롤업 젤리||premier_naturetoiletroll_2ply_20",
  "GENERAL MILLS 후르츠 롤업 젤리||premier_pulptoiletroll_3ply_30",
  "GENERAL MILLS 후르츠 롤업 젤리||the_only_bean_edamame",
  "GENERAL MILLS 후르츠 롤업 젤리||vinda_deluxeprestige4d_3ply_16",
  "GENERAL MILLS 후르츠 롤업 젤리||vinda_deluxetoiletpaper_smooth_3ply_16",
  "GENERAL MILLS 후르츠 롤업 젤리||vinda_deluxetoiletpaper_smooth_3ply_8",
  "GENERAL MILLS 후르츠 롤업 젤리||vinda_deluxetoiletpaper_smoothfeel_3ply_24",
  "GENERAL MILLS 후르츠 롤업 젤리||vinda_prestige4d_cameliascented_3ply_16",
  "GENERAL MILLS 후르츠 롤업 젤리||vinda_prestige4d_decoembossed_3ply_8",
  "GENERAL MILLS 후르츠거거셔스 젤리||bika_chickengreensnacks",
  "GENERAL MILLS 후르츠거거셔스 젤리||dutch_lady_instantfilledmilkpowder_honey",
  "GENERAL MILLS 후르츠거거셔스 젤리||fn_evaporatedfilledmilk",
  "GENERAL MILLS 후르츠거거셔스 젤리||fn_filledmilk_sweetenedcondensed",
  "GENERAL MILLS 후르츠거거셔스 젤리||marigold_evaporatedfilledmilk",
  "GENERAL MILLS 후르츠거거셔스 젤리||pureen_waterfilledteether",
  "GENERAL MILLS 후르츠거거셔스 젤리||sheba_tunainjelly",
  "HEINZ 클레시코 알프레도소스||franks_redhot_originalcayenne",
  "JUVER 레몬에이드||alder_creek_giftbasket_lemonade",
  "JUVER 레몬에이드||baida_rock_poppingcandylemonade",
  "JUVER 레몬에이드||lemonade_giftcard_50multipack",
  "KASUGAI 와사비콩 스낵 (그린피스+잠두)||giorgio_mushroompiecesstems",
  "KASUGAI 와사비콩 스낵 (그린피스+잠두)||le_sueur_veryyoungsmallsweetpeas",
  "LES COMTES DE PROVENCE 딸기잼||cvmallow_strawberryjam_marshmallow",
  "LES COMTES DE PROVENCE 딸기잼||daiichipan_pokemonpikachu_pancake_strawberryjamwhip",
  "LES COMTES DE PROVENCE 딸기잼||izutsu_merlot_mastersommelier",
  "LES COMTES DE PROVENCE 딸기잼||kanshindo_benihoppe_strawberrymilk",
  "LES COMTES DE PROVENCE 딸기잼||mikuro_seika_strawberryjamsandcookie",
  "LES COMTES DE PROVENCE 딸기잼||pasco_tsubustrawberryjambread",
  "LES COMTES DE PROVENCE 딸기잼||puda_pinotnoir",
  "LES COMTES DE PROVENCE 딸기잼||smuckers_uncrustables_pbstrawberryjam",
  "LES COMTES DE PROVENCE 딸기잼||yamazaki_lunchpack_strawberryjammargarine",
  "LES COMTES DE PROVENCE 멀티베리 스프레드||amazin_graze_antioxidantberrytrailmix",
  "LES COMTES DE PROVENCE 멀티베리 스프레드||anlene_lowfatmixedberriesyogurt",
  "LES COMTES DE PROVENCE 멀티베리 스프레드||buttercup_dairyspread",
  "LES COMTES DE PROVENCE 멀티베리 스프레드||buttercup_tubluxuryspread",
  "LES COMTES DE PROVENCE 멀티베리 스프레드||ced_almondspread",
  "LES COMTES DE PROVENCE 멀티베리 스프레드||ced_cashewspread",
  "LES COMTES DE PROVENCE 멀티베리 스프레드||daiso_sanriofrappe_keychain_mixberry",
  "LES COMTES DE PROVENCE 멀티베리 스프레드||delfi_chocospread",
  "LES COMTES DE PROVENCE 멀티베리 스프레드||extra_chunky_avocadospread",
  "LES COMTES DE PROVENCE 멀티베리 스프레드||farm_fresh_yogurtdrink_mixedberries",
  "LES COMTES DE PROVENCE 멀티베리 스프레드||fernleaf_lowfatyogurt_mixedberry",
  "LES COMTES DE PROVENCE 멀티베리 스프레드||lactel_fatfreeyogurt_mixedberriesappleacai",
  "LES COMTES DE PROVENCE 멀티베리 스프레드||lactel_smoothlowfatyogurt_mixedberries",
  "LES COMTES DE PROVENCE 멀티베리 스프레드||love_earth_almondchiaspread",
  "LES COMTES DE PROVENCE 멀티베리 스프레드||love_earth_hazelnutchocolatespread",
  "LES COMTES DE PROVENCE 멀티베리 스프레드||malee_berrymixedapplepomegranate",
  "LES COMTES DE PROVENCE 멀티베리 스프레드||marigold_100pearmixedberries",
  "LES COMTES DE PROVENCE 멀티베리 스프레드||marigold_fatfreeyogurt_mixedberries_130g",
  "LES COMTES DE PROVENCE 멀티베리 스프레드||marigold_fatfreeyogurt_mixedberries_470g",
  "LES COMTES DE PROVENCE 멀티베리 스프레드||marigold_fatfreeyogurtdrink_mixedberries",
  "LES COMTES DE PROVENCE 멀티베리 스프레드||mentos_coolchews_mixedberrymint",
  "LES COMTES DE PROVENCE 멀티베리 스프레드||milna_naturepuff_applemixberry",
  "LES COMTES DE PROVENCE 멀티베리 스프레드||naturel_litespread",
  "LES COMTES DE PROVENCE 멀티베리 스프레드||naturel_olivespread",
  "LES COMTES DE PROVENCE 멀티베리 스프레드||nutella_chocolatespread_680g",
  "LES COMTES DE PROVENCE 멀티베리 스프레드||nuttelex_margarinespread_buttery",
  "LES COMTES DE PROVENCE 멀티베리 스프레드||snow_softspread",
  "LES COMTES DE PROVENCE 멀티베리 스프레드||sun_up_gold_mixedberryconcentrated",
  "LES COMTES DE PROVENCE 멀티베리 스프레드||sunquick_selectmixedberries",
  "LES COMTES DE PROVENCE 멀티베리 스프레드||symphony_spread_blacksesamecream",
  "LES COMTES DE PROVENCE 멀티베리 스프레드||symphony_spread_hazelnutchocolatecream",
  "LES COMTES DE PROVENCE 멀티베리 스프레드||symphony_spread_pistachiocream",
  "LES COMTES DE PROVENCE 멀티베리 스프레드||twin_cows_blendedspread",
  "LES COMTES DE PROVENCE 멀티베리 스프레드||unif_allyouneed_mixedgojiberryjuice",
  "LES COMTES DE PROVENCE 멀티베리 스프레드||vaseline_originalpetroleumjelly",
  "LIKE AIR 퍼프콘 클래식||riska_moistchocolate_180g",
  "MAILLE 홀그레인 머스타드||heinz_tomatoketchup_44oz3pk",
  "MAILLE 홀그레인 머스타드||hellmanns_realmayonnaise_64oz",
  "MAILLE 홀그레인 머스타드||miracle_whip_original_1gal",
  "MAILLE 홀그레인 머스타드||miracle_whip_original_30oz2pk",
  "MCCAIN 해쉬브라운 감자||armour_star_cornedbeefhash_hearty",
  "MISURA 통밀 크래커||anchor_wheatflour",
  "MISURA 통밀 크래커||angel_beanpaste_whole",
  "MISURA 통밀 크래커||aqina_pineapplewholechicken",
  "MISURA 통밀 크래커||cap_lili_wheatflour",
  "MISURA 통밀 크래커||del_monte_wholekernelcorn_380g",
  "MISURA 통밀 크래커||edsam_wheat_bijigandum",
  "MISURA 통밀 크래커||ensure_goldwheat_800g",
  "MISURA 통밀 크래커||farmlove_wholechicken",
  "MISURA 통밀 크래커||gardenia_branwheatgerm",
  "MISURA 통밀 크래커||generic_chicken_wholeleg_500g",
  "MISURA 통밀 크래커||generic_friedchicken_wholeleg_original",
  "MISURA 통밀 크래커||generic_friedchicken_wholeleg_spicy",
  "MISURA 통밀 크래커||generic_marinatedchicken_wholeleg",
  "MISURA 통밀 크래커||generic_wholeduck",
  "MISURA 통밀 크래커||glucerna_wheat_800g",
  "MISURA 통밀 크래커||gps_wheatflour",
  "MISURA 통밀 크래커||hosen_wholemushroom",
  "MISURA 통밀 크래커||letgo_raya26rug_wheatcheck",
  "MISURA 통밀 크래커||massimo_100wholewheat",
  "MISURA 통밀 크래커||massimo_sandwichloaf_wheatgerm",
  "MISURA 통밀 크래커||mccormick_blackpepperwhole",
  "MISURA 통밀 크래커||narcissus_wholemushroom",
  "MISURA 통밀 크래커||nestle_cerelacwheat_honey_225g",
  "MISURA 통밀 크래커||nestle_cerelacwheat_honeydha",
  "MISURA 통밀 크래커||nutrigen_wholemilk",
  "MISURA 통밀 크래커||orchid_taucusauce_whole",
  "MISURA 통밀 크래커||prodiet_cat_wholemackerel",
  "MISURA 통밀 크래커||singlong_mixedherbswhole",
  "MISURA 통밀 크래커||singlong_oreganowhole",
  "OLITALIA 엑스트라버진 올리브유||ayam",
  "OLITALIA 엑스트라버진 올리브유||tc_boy_tuna",
  "OLITALIA 엑스트라버진 올리브유||tokushima_sangyo",
  "OTTAVIO 아보카도 오일||sb_food_seasoning_avocado_tomato_salad",
  "OTTAVIO 포도씨유||crisco_allvegetableshortening",
  "OTTAVIO 포도씨유||plantlife_eveningprimroseoil",
  "OTTAVIO 포도씨유||plantlife_sweetalmondoil",
  "OTTAVIO 포도씨유||wells_oil_sesamecarrieroil",
  "PM SWEET 36 마카롱||absolutely_gluten_free_chocolate",
  "PM SWEET 36 마카롱||absolutely_gluten_free_chocolate_coconut",
  "PM SWEET 36 마카롱||absolutely_gluten_free_coconut",
  "PM SWEET 36 마카롱||crown_homestyle_coconut",
  "PM SWEET 36 마카롱||golden_coconut_regular",
  "PM SWEET 36 마카롱||jennies_coconut",
  "PM SWEET 36 마카롱||jennies_organic_coconut",
  "PM SWEET 36 마카롱||jennies_organic_double_chocolate_sea_salt",
  "PM SWEET 36 마카롱||la_bayamesa_coconut",
  "PM SWEET 36 마카롱||lazzaroni_amaretti_di_saronno",
  "PM SWEET 36 마카롱||mrs_crimbles_chocolate_coconut",
  "PM SWEET 36 마카롱||pandalab_gel_food_coloring",
  "PM SWEET 36 마카롱||toasted_old_fashioned_recipe_coconut",
  "RAGU 토마토 파스타소스||tabasco_cayennegarlic",
  "RAO'S 마리나라소스||adabi_seafood",
  "RAO'S 마리나라소스||angel_oyster",
  "RAO'S 마리나라소스||cj_topokki",
  "RAO'S 마리나라소스||ck_divided_sauce_plate",
  "RAO'S 마리나라소스||claytan_square_sauce_dish",
  "RAO'S 마리나라소스||daves_gourmet_ghost_pepper",
  "RAO'S 마리나라소스||daves_gourmet_insanity",
  "RAO'S 마리나라소스||ferry_fish",
  "RAO'S 마리나라소스||ferry_pomfret_fish",
  "RAO'S 마리나라소스||fortune_abalone",
  "RAO'S 마리나라소스||gardens_chilli",
  "RAO'S 마리나라소스||hp_sauce",
  "RAO'S 마리나라소스||kikkoman_bulgogi",
  "RAO'S 마리나라소스||kikkoman_mirin",
  "RAO'S 마리나라소스||kikkoman_sweet",
  "RAO'S 마리나라소스||lea_perrins",
  "RAO'S 마리나라소스||lee_kum_kee_barbeque",
  "RAO'S 마리나라소스||life_black_pepper",
  "RAO'S 마리나라소스||life_oyster",
  "RAO'S 마리나라소스||maggi_chili",
  "RAO'S 마리나라소스||maggi_oyster",
  "RAO'S 마리나라소스||orchid_soy",
  "RAO'S 마리나라소스||rasto_chipotle",
  "RAO'S 마리나라소스||rasto_tartar",
  "RAO'S 마리나라소스||red_boat_fish",
  "RAO'S 마리나라소스||squid_fish",
  "RAO'S 마리나라소스||tabasco_cayenne_garlic_pepper",
  "RAO'S 마리나라소스||tabasco_pepper",
  "RAO'S 마리나라소스||tabasco_sriracha",
  "RAO'S 마리나라소스||tiparos_fish",
  "S&B 골든카레 (중간맛/매운맛)||authentic_dashi_pack",
  "S&B 골든카레 (중간맛/매운맛)||mishima_crunchy_garlic_chili_sauce",
  "S&B 골든카레 (중간맛/매운맛)||nissin_cup_noodles_protein_hot_spicy_chicken",
  "S&B 골든카레 (중간맛/매운맛)||pacific_bone_broth_unsalted",
  "S&B 골든카레 (중간맛/매운맛)||segar2go_cucumber",
  "S&B 골든카레 (중간맛/매운맛)||yamaroku_shoyu",
  "S&B생와사비||hapi_wasabi_green_peas",
  "S&B생와사비||kame_rice_cracker_wasabi",
  "S&B생와사비||kinders_buffalo_wing_sauce",
  "S&B생와사비||kinders_stuffing_mix",
  "S&B생와사비||kinders_teriyaki_marinade",
  "S&B생와사비||kinders_wing_dipping_sauce",
  "S&B생와사비||oceans_halo_wasabi_seaweed_snack",
  "TENKEI 종합 모나카||generic_book_monaka_morinaka_iga_marta",
  "TENKEI 종합 모나카||generic_book_monaka_toyama_gentle_love_slave",
  "TENKEI 종합 모나카||generic_book_morinaka_monaka_young_ladies",
  "TENKEI 종합 모나카||generic_book_natsume_monaka_tamer",
  "TENKEI 종합 모나카||heinz_bbq_sauce_hickory_smoke",
  "TIPCO 오렌지자몽주스 (착즙)||artline_paint_marker_orange",
  "TIPCO 오렌지자몽주스 (착즙)||deer_creek_compass_orange",
  "TIPCO 오렌지자몽주스 (착즙)||fruitstop_valencia_orange",
  "TIPCO 오렌지자몽주스 (착즙)||generic_egypt_valencia_orange",
  "TIPCO 오렌지자몽주스 (착즙)||generic_sa_grapefruit",
  "TIPCO 오렌지자몽주스 (착즙)||jinro_grapefruit_soju",
  "TIPCO 오렌지자몽주스 (착즙)||lux_shower_grapefruit",
  "TIPCO 오렌지자몽주스 (착즙)||parker_im_vibrant_rollerball_pen",
  "TIPCO 오렌지자몽주스 (착즙)||pilot_juiceup_refill",
  "TIPCO 오렌지자몽주스 (착즙)||pilot_juiceup_rollerball",
  "TIPCO 오렌지자몽주스 (착즙)||stabilo_swingcool_highlighter_orange",
  "TIPCO 오렌지자몽주스 (착즙)||true_citrus_grapefruit",
  "TIPCO 오렌지자몽주스 (착즙)||true_citrus_orange",
  "TIPCO 오렌지자몽주스 (착즙)||true_citrus_orange_mango",
  "TIPCO 오렌지자몽주스 (착즙)||vitagen_cultured_milk_orange",
  "TIPCO 파인애플주스 (착즙)||stur_coconut_pineapple",
  "TIPCO 파인애플주스 (착즙)||sunkist_soda_pineapple_mix",
  "네스카페 테이스터스 초이스커피||uji_no_tsuyu_iyemon_decafgreentea",
  "네이처밸리 트레일 믹스바||wheat_chex_cereal",
  "네이처밸리 프로틴바||glucerna_shake_creamychoc",
  "네이처밸리 프로틴바||premier_protein_shake_lemonbar",
  "데체코 바질페스토||i_love_pesto_tshirt",
  "덴로쿠 스낵믹스 (개별포장 믹스)||ecobrowns_goldwholegrainricemix",
  "덴로쿠 스낵믹스 (개별포장 믹스)||farms_essence_currychickenrice",
  "덴로쿠 스낵믹스 (개별포장 믹스)||farms_essence_roastedchickendrumstickrice",
  "덴로쿠 스낵믹스 (개별포장 믹스)||farms_essence_roastedchickenrice",
  "덴로쿠 스낵믹스 (개별포장 믹스)||farms_essence_steamchickenrice",
  "덴로쿠 스낵믹스 (개별포장 믹스)||home_perfect_japanesechopsticks",
  "덴로쿠 스낵믹스 (개별포장 믹스)||jati_glutinousriceflour",
  "덴로쿠 스낵믹스 (개별포장 믹스)||la_boheme_cheesecake",
  "덴로쿠 스낵믹스 (개별포장 믹스)||la_boheme_redbeanbun",
  "덴로쿠 스낵믹스 (개별포장 믹스)||meriah_mixcolourrice",
  "덴로쿠 스낵믹스 (개별포장 믹스)||moghul_faizabasmathirice",
  "덴로쿠 스낵믹스 (개별포장 믹스)||nestle_cerelac_ricemixedfruits",
  "덴로쿠 스낵믹스 (개별포장 믹스)||nestle_cerelac_ricemixedvegetables",
  "덴로쿠 스낵믹스 (개별포장 믹스)||singlong_hainanesechickenricemix",
  "덴로쿠 스낵믹스 (개별포장 믹스)||sunflower_embryo_brownrice",
  "덴로쿠 스낵믹스 (개별포장 믹스)||thai_king_brownrice",
  "맥비티 다이제스티브 투고||otis_spunkmeyer_variety_muffins",
  "맥비티 다이제스티브 투고||thomas_original_englishmuffins",
  "본마망 4프루츠잼||mrs_wages_citricacid",
  "본마망 무화과잼||vaseline_original_petroleumjelly",
  "스키피 크런치 땅콩버터||generic_pbblacksesamebars",
  "스키피 크런치 땅콩버터||nugo_slim_crunchypeanutbutter",
  "스키피 크런치 땅콩버터||reeses_nutrageous",
  "스키피 크리미 땅콩버터||mms_peanutbutter_partysize",
  "스키피 크리미 땅콩버터||reeses_fastbreak",
  "스키피 크리미 땅콩버터||reeses_pieces",
  "오리히로 과일 곤약젤리||biolore_mangopineapplejam",
  "오리히로 과일 곤약젤리||crofters_apricotjelly",
  "오리히로 과일 곤약젤리||generic_gelatin_powder_unflavored",
  "오리히로 과일 곤약젤리||good_good_concordgrapejelly",
  "오리히로 과일 곤약젤리||smuckers_assorted_jamjellycups",
  "오리히로 과일 곤약젤리||smuckers_squeeze_grapefruitspread",
  "오리히로 과일 곤약젤리||smuckers_uncrustables_pbgrapejelly",
  "오리히로 과일 곤약젤리||tabasco_classicpepperjelly",
  "오리히로 과일 곤약젤리||tabasco_jalapenopepperjelly",
  "오리히로 과일 곤약젤리||vaseline_original_petroleumjelly",
  "이금기 프리미엄 굴소스||a1_originalsteaksauce",
  "이금기 프리미엄 굴소스||ajinomoto_cookdo_qingjiaorousi",
  "이금기 프리미엄 굴소스||chef_mate_countrysausagegravy",
  "이금기 프리미엄 굴소스||glico_babyfood_vegmapodon",
  "이금기 프리미엄 굴소스||glico_babyfood_whitefishhappousai",
  "이금기 프리미엄 굴소스||hankyu_delica_whitefishvegoystersauce",
  "이금기 프리미엄 굴소스||healthy_boy_sweetsoysauce",
  "이금기 프리미엄 굴소스||kewpie_babyfood_fishbento",
  "이금기 프리미엄 굴소스||kewpie_babyfood_livervegtomatobento",
  "이금기 프리미엄 굴소스||kewpie_babyfood_westernbento",
  "이금기 프리미엄 굴소스||kinders_goldlabelbbqsauce_variety",
  "이금기 프리미엄 굴소스||louisiana_fish_fry_cocktailsauce",
  "이금기 프리미엄 굴소스||maruchan_yakisoba_shanghaioystersauce",
  "이금기 프리미엄 굴소스||mi_the_food_mapoeggplant",
  "이금기 프리미엄 굴소스||mi_the_food_mapotofu_mediumspicy",
  "이금기 프리미엄 굴소스||myojo_chukasanmai_akasakarikyu",
  "이금기 프리미엄 굴소스||nichirei_minispringrolls",
  "이금기 프리미엄 굴소스||nissin_shanghaiyakisoba_large",
  "이금기 프리미엄 굴소스||osaka_ohsho_xiaolongbao",
  "이금기 프리미엄 굴소스||otafuku_sushieelsauce",
  "이금기 프리미엄 굴소스||red_boat_fishsauce",
  "이금기 프리미엄 굴소스||sagamiya_atsuage_oystersauce",
  "이금기 프리미엄 굴소스||sb_donburito_chukadon",
  "이금기 프리미엄 굴소스||sweet_baby_rays_originalbbq",
  "카네후쿠 짜먹는 명란젓갈||big_bobs_bellybuster_battered_pollockfillet",
  "카네후쿠 짜먹는 명란젓갈||crab_roe_generic",
  "카네후쿠 짜먹는 명란젓갈||entree_redi_iqf_pollockminitender",
  "카네후쿠 짜먹는 명란젓갈||entree_redi_pollockloinportions",
  "카네후쿠 짜먹는 명란젓갈||frozen_seafood_generic_pollock",
  "카네후쿠 짜먹는 명란젓갈||ghosthorn_fishingrodreelcombo",
  "카네후쿠 짜먹는 명란젓갈||icelandic_samband_pollockfillet",
  "카네후쿠 짜먹는 명란젓갈||king_and_prince_mrsfridays_gourmetbreadedpollock",
  "카네후쿠 짜먹는 명란젓갈||live_ocean_cohosalmon_thaichilibutter",
  "카네후쿠 짜먹는 명란젓갈||mrs_fridays_craftbeerbattered_pollock",
  "카네후쿠 짜먹는 명란젓갈||mrs_fridays_tavernbattered_pollockfillet",
  "카네후쿠 짜먹는 명란젓갈||nippon_ham_mayokaraage",
  "카네후쿠 짜먹는 명란젓갈||pubhouse_battered_bonelesspollockfillets",
  "카네후쿠 짜먹는 명란젓갈||sharktrue_butcherstwine",
  "카네후쿠 짜먹는 명란젓갈||viking_nordica_breadedpollockfillet",
  "카네후쿠 짜먹는 명란젓갈||viking_potatocrunch_pollockstick",
  "카네후쿠 짜먹는 명란젓갈||viking_wholegrainrich_pollockfillet",
  "퀘이커 심플리그래놀라||nippon_yakken_kinnoaojiru",
  "크리스피 코코넛롤||ayamas_crispynuggets",
  "크리스피 코코넛롤||cocoli_coconutoil",
  "크리스피 코코넛롤||cutie_compacttoiletroll",
  "크리스피 코코넛롤||cutie_softtoiletroll",
  "크리스피 코코넛롤||daiso_lintrollerrefill",
  "크리스피 코코넛롤||daiso_lintrollerrefill_floor",
  "크리스피 코코넛롤||daiso_lintrollerrefill_pethair",
  "크리스피 코코넛롤||kleenex_regular",
  "크리스피 코코넛롤||kleenex_ultrasoft_aloevera",
  "크리스피 코코넛롤||kleenex_ultrasoft_fresh",
  "크리스피 코코넛롤||kleenex_ultrasoft_regular",
  "크리스피 코코넛롤||kleenex_ultrasoft_thick",
  "크리스피 코코넛롤||lazat_otakotak_chillicrab",
  "크리스피 코코넛롤||lazat_otakotak_nyonyakunyit",
  "크리스피 코코넛롤||mixue_coconutjelly_milktea_large",
  "크리스피 코코넛롤||mixue_coconutjelly_milktea_medium",
  "크리스피 코코넛롤||nissin_crispycrackers_lemon",
  "크리스피 코코넛롤||nutriplus_crispyfriedchicken",
  "크리스피 코코넛롤||premier_floraltoiletroll",
  "크리스피 코코넛롤||premier_naturetoiletroll",
  "크리스피 코코넛롤||premier_pulptoiletroll",
  "크리스피 코코넛롤||rasaku_coconutmilk",
  "크리스피 코코넛롤||salanova_crispylettuce",
  "크리스피 코코넛롤||sunbelt_bakery_chewygranolabars_fudgedippedcoconut",
  "크리스피 코코넛롤||sushi_crispy_tender_handroll",
  "크리스피 코코넛롤||ufc_coconutwater",
  "크리스피 코코넛롤||vinda_deluxe_smooth",
  "크리스피 코코넛롤||vinda_deluxeprestige4d",
  "크리스피 코코넛롤||vinda_prestige4d_cameliascented",
  "크리스피 코코넛롤||vinda_prestige4d_deco",
  "크리스피롤 12곡||fsstam_originalcandywafer_6roll",
  "크리스피롤 12곡||little_debbie_swissrolls_36ct",
  "크리스피롤 12곡||necco_originalassorted_24ct",
  "크리스피롤 12곡||necco_originalcandywafer_generic",
  "크리스피롤 12곡||necco_wafers_chocolate_displaypack_24",
  "크리스피롤 12곡||necco_wafers_original_24pk",
  "크리스피롤 12곡||necco_wafers_original_6pk",
  "크리스피롤 12곡||necco_wafers_originalchocolate_6roll",
  "타바스코핫소스||bachans_bbq_original",
  "타바스코핫소스||cirio_pastasauce_calabria_hotchilli",
  "타바스코핫소스||guy_fieri_topsecret_creamygarlic",
  "타바스코핫소스||haidilao_herbsspices",
  "타바스코핫소스||haidilao_kimchi",
  "타바스코핫소스||haidilao_nanyangcurry",
  "타바스코핫소스||haidilao_shrimp",
  "타바스코핫소스||haidilao_tomato",
  "타바스코핫소스||sb_golden_curry_mediumhot",
  "타바스코핫소스||thai_kitchen_redcurrypaste",
  "타바스코핫소스||torani_puremade_caramel",
  "타바스코핫소스||velveeta_cheesesauce_original",
  "트롤리 올인원 젤리||parade_cottoncandy",
  "트롤리 올인원 젤리||sweet_candy_saltwatertaffy_assorted",
  "페레로 누텔라||smuckers_uncrustables_chochazelnut",
  "프링글스 사워크림&어니언 멀티팩||farm_fresh_fullcreammilk",
  "하리보 골드베렌||ecokind_gummybear_compositionbook",
  "하리보 골드베렌||gummy_glow_fruitywaxcandy",
  "하리보 골드베렌||hemp_gummies_sleep",
  "하리보 골드베렌||silicone_gummy_mold",
  "하리보 메가 파티 젤리||daiso_spongevariety",
  "하리보 메가 파티 젤리||yogood_glowparfait_muesli_variety",
  "하리보 스타믹스젤리||nomura_irimame_millebiscuit_cornpotage",
  "하리보 푸르티부시||gruns_immunitygummies",
  "하인즈 굿마요네즈||aeon_bakery_cornmayobread",
  "하인즈 굿마요네즈||aeon_bakery_wienerroll",
  "하인즈 굿마요네즈||aeon_deli_coleslaw",
  "하인즈 굿마요네즈||aeon_deli_gobosalad_small",
  "하인즈 굿마요네즈||aeon_deli_shrimpsalad_tartar",
  "하인즈 굿마요네즈||kuhne_friedonion",
  "하인즈 굿마요네즈||mascot_dillweed",
  "하인즈 굿마요네즈||mccormick_anchovygarlicdressing",
  "하인즈 굿마요네즈||myojo_ippeichan_yakisoba_regular",
  "하인즈 굿마요네즈||nissin_chilled_futomen_yakisoba",
  "하인즈 굿마요네즈||old_fashion_nachosqueezecheese",
  "하인즈 굿마요네즈||umios_chickenmayocutlet",
  "하인즈 굿마요네즈||yamazaki_lunchpack_hammayo",
  "하인즈 굿마요네즈||yuki_foods_choregidressing",
  "하인즈 굿마요네즈||yuki_foods_dipsauce_bagnacauda",
  "하인즈 굿마요네즈||yuki_foods_sesamecreamydressing",
  "하인즈 토마토 케찹||aeon_bakery_heartyfrank",
  "하인즈 토마토 케찹||aeon_bakery_wienerroll",
  "후룻 바이 풋||cornae_americancornsnack",
  "후룻 바이 풋||corntoz_cornsnack",
  "후룻 바이 풋||cutie_compacttoiletroll_2x10",
  "후룻 바이 풋||cutie_softtoiletroll_30",
  "후룻 바이 풋||daiso_carpetcleaningtape_spiral_90",
  "후룻 바이 풋||daiso_refillroll_lintroller_90",
  "후룻 바이 풋||daiso_refillroll_lintroller_floor_50",
  "후룻 바이 풋||daiso_refillroll_lintroller_pethair_50",
  "후룻 바이 풋||haitai_sweetpotatosnack",
  "후룻 바이 풋||kelloggs_frostiessnack",
  "후룻 바이 풋||kleenex_bathtissue_regular_3ply_30",
  "후룻 바이 풋||kleenex_bathtissue_ultrasoftaloevera_20",
  "후룻 바이 풋||kleenex_bathtissue_ultrasoftfresh_20",
  "후룻 바이 풋||kleenex_bathtissue_ultrasoftregular_10",
  "후룻 바이 풋||kleenex_bathtissue_ultrasoftregular_20",
  "후룻 바이 풋||kleenex_bathtissue_ultrasoftthick_4ply_20",
  "후룻 바이 풋||manjun_crispyseaweed_habanero",
  "후룻 바이 풋||miaow_miaow_greenpeassnack",
  "후룻 바이 풋||premier_floraltoiletroll_300s_10",
  "후룻 바이 풋||premier_naturetoiletroll_2ply_20",
  "후룻 바이 풋||premier_pulptoiletroll_3ply_30",
  "후룻 바이 풋||snek_ku_tamtam_crabflavor",
  "후룻 바이 풋||sunmaid_californiaraisins_minisnack",
  "후룻 바이 풋||vinda_deluxeprestige4d_3ply_16",
  "후룻 바이 풋||vinda_deluxetoiletpaper_smooth_3ply_16",
  "후룻 바이 풋||vinda_deluxetoiletpaper_smooth_3ply_8",
  "후룻 바이 풋||vinda_deluxetoiletpaper_smoothfeel_3ply_24",
  "후룻 바이 풋||vinda_prestige4d_cameliascented_3ply_16",
  "후룻 바이 풋||vinda_prestige4d_decoembossed_3ply_8",
]);
